export const ISI_DOKTER = [
  {
    id: 1,
    nama: "Dr. Maya Puspita Sari",
    spesialis: "Dokter Spesialis Penyakit Dalam",
    rating: 4.7,
    pengalaman: "8 tahun",
    foto: "/dokter/dokter-1.png",
    harga: "Rp 55.000 - Rp 300.000",
  },
  {
    id: 2,
    nama: "Dr. Eka Wijaya W",
    spesialis: "Dokter Umum",
    rating: 4.5,
    pengalaman: "4 tahun",
    foto: "/dokter/dokter-2.png",
    harga: "Rp 22.500 - Rp 250.000",
  },
  {
    id: 3,
    nama: "Dr. Allif Maulana Syafrin",
    spesialis: "Dokter Spesialis Penyakit Dalam",
    rating: 4.8,
    pengalaman: "7 tahun",
    foto: "/dokter/dokter-3.png",
    harga: "Rp 55.000 - Rp 300.000",
  },
  {
    id: 4,
    nama: "Dr. Vera Bahar",
    spesialis: "Dokter Spesialis Penyakit Dalam",
    rating: 4.5,
    pengalaman: "10 tahun",
    foto: "/dokter/dokter-3.png",
    harga: "Rp 55.000 - Rp 350.000",
  },
  {
    id: 5,
    nama: "Dr. Nuriati Harahap",
    spesialis: "Dokter Umum",
    rating: 4.5,
    pengalaman: "8 tahun",
    foto: "/dokter/dokter-1.png",
    harga: "Rp 55.000 - Rp 300.000",
  },
];
